.EQ
delim $$
.EN
.TL
Climate Change and Energy ( blog #6 )
.AU
Cathal O'Grady
.AI
DCU
.LP
This blog discusses climate change and energy. The topic of energy being our
expenditure of oil reserves, and the topic of climate change being how our
actions are promoting rapid change in our earths climate.

These two topics are very much linked, in so much as our increasing use of oil
releasing $co sup 2$, there is a shift in average global temperature. In this
way by solving the problem of expending oil, we directly reduce our impact on
the climate.

I categorise two key areas of change needed in order to stunt the rate
of climate change and the growing lack of energy, the individual and the 
governmental/enterprise. Though governmental change is the most important.

It is frustrating that despite the clear need for change no meaningful change
has come. Is it on us to innovate and come up with a solution that companies
and governments can't refuse? I don't think so. Though the future is clear, 
whether people like it or not, energy will run out and it is a matter of us
being prepared or not.

Development of sustainable and even fully renewable energy is well under way
and even put in place already. I am personally optimistic of nuclear energy, 
nuclear fission plants are highly secure and safe these days, despite past
events and the prospects of nuclear fusion seem promising. Although nuclear
energy has an immense upfront cost and people don't fully trust it due to
it's history.

Depending on the climate wind energy is also a viable option, in the case of
the Orkney Islands in Scotland[1] they have a surplus of energy year round supplied
entirely by wind energy. For warmer climates, solar energy seems a promising 
option too, especially as the technology improves and efficiency is better.
Aptera[2] have already released a car that boasts 40 miles of driving per day purely from
solar energy.

Though climate change and energy issues seem to spark innovation in many, currently
it is more convenient to damage the environment and use non-sustainable energy than
pursuing the more ethical options. This is why governments need to instill 
stricter regulation on such practices.

.UL "References:"

.BI
[1] https://www.youtube.com/watch?v=8UmsfXWzvEA

[2] https://aptera.us/

.TL
Blog #7, Topic: the Internet
.AU
Cathal O'Grady
.AI
DCU
.LP
I got my first smart phone when I was 12 years old. This was the gateway into
the world I would come very familiar of in the coming years. At first I used
my phone to message my friends and organize meet-ups on an online messaging
app(kik), this was very helpful and saved us calling for each other one by
one. It seemed as more of a convenient tool than a necessity.

I was pushed to get instagram, though I wasn't consumed by it like I could see
my peers had been. I used it purely for messaging like before. For a while I
accepted my peers were just wasting their time. But I came to realise how much the
phone was against them, and how lucky I was not to be in a similar trance.

Phones are designed for media consumption I found and the apps they had, had an
infinite supply of media. For many in my generation the only computer they have
is their phone and hence they become a helpless consumer of the internet. This
is in contrast to the 90's when people who used the internet often contributed
their part to the growing web.

With many people absorbed and even addicted to their phones, when one hears
about the kind of specialized media they are being fed by ADM algorithms, or
the kind of data that is being collected, they convince themselves they don't
care.

If we analogize ADM to somebody carefully manipulating you to get what exactly
what they wan't, you may start to see they have little place in a civil
society. I personally feel there shouldn't be a middle ground in this matter.
Are we to accept that services cannot function without monitoring and
targeted advertisement?

The future of the internet is in our hands, we mustn't trust the same companies
that have subjugated us for so long.

.TL
Sections for Business Plan ( BLOG #8 )
.AU
Cathal O'Grady
.AI
DCU
.SH
Pricing
.PP
Currently the game is free and we would like to keep it that way. Upon
registry of the business we hope to open our bank account to donations via a
separate page. We could also possibly hold raffles for donators or maybe give
exclusive stickers to donators.

As well as this we will run advertisements by default on the site. Although
we think it's reasonable to allow the user to opt out. Even at this we will
surely make good revenue as most would not look to disabling them.

Should we move onto other projects, go our separate ways or the price is
right we are willing to sell. Though we can always build on this project
as from this we have gained some reputation that may translate to
further interest in our other projects down the line.

Another route of income may be sponsorship. We could possibly get a newspaper
company to sponsor our project in return for their name on the site and 
possibly prefixing the sites domain name.

.SH
Growth Projections
.PP
To ensure that we do not get beaten by a more convenient/accessible competitor
we prospect a port of the online app to mobile devices. It is important that
we do this as soon as possible as there are likely bootleg apps already on the
market.

From this angle and a growing user base we may be able to launch new apps under
our name. We will keep an eye on our growth in the coming months and review it's
growth regularly.

In general we are looking to expand to as many platforms as possible to appeal
to as many people as possible. With this business attitude and the our
promising trends our growth is certain.

.TL
The matrix, a growing plausibility ( blog #9 )
.AU
Cathal O'Grady
.AI
DCU
.LP
The matrix had an interesting take on the future of technology.  This idea that
we are in a simulation, being quietly exploited by some higher power. Though
it's of course an extreme conspiracy to suggest the same for the world we live
in today, I do think the malice and subjugation reflects a trend in the world
as technology has increasingly sought to track and mold users. Platforms
carefully converge their users ideals in-line with that of the platform itself.

I think that the matrix is culturally important when it comes to technology and
security. It is often that people reference the "blue" and "red" pill. Taking
the blue pill is rejecting reality for the fruits blissful negligence and the
red pill, accepting reality and pursuing enlightenment in the prospects of
freedom.

Society rewards you for using devices and platforms that are malicious by
nature. In lock-down you were expected to use platforms like zoom and Microsoft
Teams, platforms that spy on and restrict users. We are expected to have mobile
phones, the perfect device for tracking our every step.

I don't like to be pessimistic, though its only justified by what increased
surveillance, tracking and reduced privacy entails.  Increasingly democracy
will become weak. Whistle blowers have little chance when their presence is
constantly under surveillance. 

In Australia law enforcement can get a warrant to have full access to a persons
online accounts. In which they can add, copy, delete or alter account
credentials and data in a computer. This warrant only needs to be granted by a
magistrate for the purpose of an investigation.[1]

Facebook or more recently Meta, are proposing a metaverse. The same company
that former employees talk of more the extreme and controversial posts being
the priority for users to see. This virtual world, "better than reality" is
eerily similar to the simulation of the matrix.

There are many more examples of the increasingly subjugating practices and
though it's still a stretch to use the matrix as a cultural touchstone for the
future of the world, hopefully you can see how the world it conveys has only
become more plausible in recent times.

.I
references:
.PP
[1] page 113: https://parlinfo.aph.gov.au/parlInfo/download/legislation/bills/r6623_aspassed/toc_pdf/20144b01.pdf;fileType=application%2Fpdf

.TL
Where I see myself outside of college ( blog #10 )
.AU
Cathal O'Grady
.AI
DCU
.LP
Technology seems to ever improve, ai and machine
learning now in the tool set of many program designers.
I don't think we can predict without reasonable doubt
whether technology will bring us together or continue to
tear us apart. Though one thing is certain, security
seems the bottleneck to all technological advancement.
Often an after thought despite the consequences it can
incur. For this reason I see myself exploring this area
down the line.

I am creative, I used to be a hardcore artist, though
when I did do art I only used a pencil. This reflects in
the way I learn and interact with the things around me.
I am like a single threaded computer, able to throw
myself all at one discipline, ineffective at jumping
between varying tasks or topics. In this way I do seen
myself engrossed in my career, likely security or
systems administration

I am optimistic that in the future linux or some unix
like system will overthrown Microsoft's windows. If the
kernel can dominate the mobile space it surely can
dominate the desktop too. I would predict as linux
becomes more popular, Microsoft will likely distribute
its own version to try and capitalize.

As I alluded to and as you can imagine, being a fond
linux user, I am also suited to a systems administration
job. This is something I have been looking into and I think
it suits my strengths and passions. Security would also come
into systems administration.

In general I have some sense of my place in the future and
what the future might hold and I am optimistic in the sense
that I will be doing something I truly enjoy.

.TL
Thoughts on the course
.LP
As frustrating as they were at times, I do like the weekly
blogs. They forced me to write about topics I would
otherwise not express my views about. Though I do think that
they could be bi-weekly rather than weekly, or at least only
on weeks without other assignments for the module.

The lecture content was also great in my opinion, though
maybe a couple more videos, or more questions to the
students now and then and it would make for even better
engagement.

The one thing I didn't really like about the module was that
we couldn't choose our groups. It is less realistic that you
would randomly meet people you don't know and design a product
or make a startup. I feel the group project is missing a big
part of startups in finding a great team, in which everybody
gets along.
