.EQ
delim $$
.EN
.TL
Climate Change and Energy
.AU
Cathal O'Grady
.AI
DCU
.LP
This blog discusses climate change and energy. The topic of energy being our
expenditure of oil reserves, and the topic of climate change being how our
actions are promoting rapid change in our earths climate.

These two topics are very much linked, in so much as our increasing use of oil
releasing $co sup 2$, there is a shift in average global temperature. In this
way by solving the problem of expending oil, we directly reduce our impact on
the climate.

I categorise two key areas of change needed in order to stunt the rate
of climate change and the growing lack of energy, the individual and the 
governmental/enterprise. Though governmental change is the most important.

It is frustrating that despite the clear need for change no meaningful change
has come. Is it on us to innovate and come up with a solution that companies
and governments can't refuse? I don't think so. Though the future is clear, 
whether people like it or not, energy will run out and it is a matter of us
being prepared or not.

Development of sustainable and even fully renewable energy is well under way
and even put in place already. I am personally optimistic of nuclear energy, 
nuclear fission plants are highly secure and safe these days, despite past
events and the prospects of nuclear fusion seem promising. Although nuclear
energy has an immense upfront cost and people don't fully trust it due to
it's history.

Depending on the climate wind energy is also a viable option, in the case of
the Orkney Islands in Scotland[1] they have a surplus of energy year round supplied
entirely by wind energy. For warmer climates, solar energy seems a promising 
option too, especially as the technology improves and efficiency is better.
Aptera[2] have already released a car that boasts 40 miles of driving per day purely from
solar energy.

Though climate change and energy issues seem to spark innovation in many, currently
it is more convenient to damage the environment and use non-sustainable energy than
pursuing the more ethical options. This is why governments need to instill 
stricter regulation on such practices.

.UL "References:"

.BI
[1] https://www.youtube.com/watch?v=8UmsfXWzvEA

[2] https://aptera.us/

